-- 000018_demo_fields.down.sql
ALTER TABLE IF EXISTS demos DROP COLUMN IF EXISTS status;
ALTER TABLE IF EXISTS demos DROP COLUMN IF EXISTS environment;
ALTER TABLE IF EXISTS demos RENAME COLUMN category TO product;
